Exclude from fee checks if originSender is whitelisted
connext/monorepo pull request #3145
Opened 2023-01-20 02:01 UTC by wanglonghong

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2023-01-22 20:21 UTC, alexwhte commented
@wanglonghong which issue is this for?

2023-01-23 05:06 UTC, rhlsthrm commented
> @wanglonghong which issue is this for?

3136, I can see it linked to the issue.

2023-01-24 10:05 UTC, rhlsthrm approved these changes

2023-01-25 05:34 UTC, rhlsthrm requested changes
This needs to be changed so the whitelist is per chain.

2023-01-25 07:03 UTC, merged