Subgraph updates
connext/monorepo pull request #3205
Opened 2023-01-24 11:54 UTC by sanchaymittal

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes #3014 
Fixes #3102 
Fixes #3006 

## Related pull request(s)

2023-01-24 15:54 UTC, rhlsthrm approved these changes

2023-01-25 07:05 UTC, rhlsthrm requested changes
Great so far, but we need to add offchain changes to account for asset removal. We probably just need to query assets using the new status thing.

2023-01-25 09:38 UTC, sanchaymittal commented
I gonna leave those changes for another PR, not sure where we want to access that info.

2023-01-25 10:16 UTC, rhlsthrm commented
OK but the problem is this doesn't fix the linked issues unless we have the offchain side.

2023-01-25 11:04 UTC, merged