Messaging status
connext/monorepo pull request #3683
Opened 2023-03-06 10:54 UTC by sanchaymittal

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2023-03-29 15:24 UTC, wanglonghong approved these changes
Looks good to me lol

2023-03-30 05:18 UTC, rhlsthrm approved these changes

2023-03-30 05:18 UTC, rhlsthrm commented
Looks good I will add to ops.

2023-03-30 08:55 UTC, rhlsthrm requested changes

2023-03-30 08:55 UTC, rhlsthrm commented on ops/testnet/staging/backend/main.tf
Need to add this to all environments, testnet prod and mainnet.

2023-03-30 09:12 UTC, wanglonghong commented on ops/testnet/staging/backend/main.tf
https://github.com/connext/monorepo/pull/3683/commits/383cd5c4d669ea4a5118d93f35e62bca57cbd7de

2023-03-30 09:15 UTC, rhlsthrm approved these changes

2023-03-30 09:29 UTC, merged