Add bware subgraphs
connext/monorepo pull request #4283
Opened 2023-05-21 10:56 UTC by rhlsthrm

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2023-05-21 10:57 UTC, wanglonghong approved these changes

2023-05-21 10:58 UTC, sanchaymittal approved these changes

2023-05-22 01:18 UTC, liu-zhipeng requested changes

2023-05-22 01:18 UTC, liu-zhipeng commented on packages/adapters/subgraph/.graphclientrc.yml
> +            timeout: 30000 # 30 seconds
I updated stableswap subgraph to track lp token transfers. 
https://github.com/connext/monorepo/pull/4274

So we need to deploy stable swap subgraphs again, after merging into prod, I will deploy to thegraph.com

2023-05-22 12:14 UTC, closed without merging