Add ladao-xocolatl to prod allow-listing
connext/monorepo pull request #4457
Opened 2023-06-09 21:28 UTC by DaigaroCota

## Description
Adding Xocolatl MXN Stablecoin $XOC, to the production allow-listed script.

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

This pull request adds the representations by domain of Xocolatl MXN Stablecoin. 
Connext address currently has mint/burn auth in Polygon(POS), Gnosis, and BSC.
Representations were added to `MAINNET_PRODUCTION_INIT_CONFIG` object in the array of `assets` to file ~/packages/deployments/contracts/src/cli/init/config/mainnet/production.ts

## Related Issue(s)
N/A

## Related pull request(s)
[chaindata repo pull request 75](https://github.com/connext/chaindata/pull/75)

2023-06-10 07:54 UTC, rhlsthrm requested changes
For posterity, please add the other domains and set the local and adopted to address(0)!

2023-06-10 19:48 UTC, DaigaroCota commented
> For posterity, please add the other domains and set the local and adopted to address(0)!

All other domains where added for xoc. All `local` was set to address(0), and `adopted` was set to the deployed xoc address in that domain. However, only polygon-bsc-gnosis has been enabled for connext mint/burn at the moment.

2023-06-15 16:52 UTC, rhlsthrm approved these changes

2023-06-19 18:23 UTC, LayneHaber approved these changes

2023-06-19 19:04 UTC, LayneHaber approved these changes

2023-06-21 10:49 UTC, sanchaymittal approved these changes

2023-06-28 23:17 UTC, merged