Alchemix Next tokens
connext/monorepo pull request #4510
Opened 2023-06-15 03:15 UTC by Hesnicewithit

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2023-06-16 21:32 UTC, LayneHaber commented
When I simulate the whitelisting transaction, it fails at minting:

1. alUSD arb:
https://dashboard.tenderly.co/lhaber/project/simulator/d0031007-8894-4fb6-9c15-2e2ab8a2837e

2. alUSD opt:
https://dashboard.tenderly.co/lhaber/project/simulator/d91c495d-7197-4719-b5b9-86de53ab1403

This is a preliminary step in our whitelisting to ensure the bridge can mint/burn on the representation. alETH seems connext isn’t whitelisted on arbitrum-goerli, but the others are. What’s odd is it seems to call mint on the alAsset, which is failing. Can’t dig into why because the source isn’t available

2023-06-16 21:33 UTC, LayneHaber requested changes
see above re: simulations

2023-06-16 21:33 UTC, LayneHaber commented on packages/deployments/contracts/src/cli/init/config/testnet/production.ts
> +      name: "nextAlUSD",
should match the canonical symbol
```suggestion
      name: "alUSD",
```

2023-06-16 21:33 UTC, LayneHaber commented on packages/deployments/contracts/src/cli/init/config/testnet/production.ts
> +      name: "nextAlETH",
should match the canonical symbol
```suggestion
      name: "alETH",
```

2023-06-21 04:07 UTC, rhlsthrm approved these changes

2023-06-21 10:47 UTC, sanchaymittal approved these changes

2023-06-21 10:47 UTC, merged