Tf vars
connext/monorepo pull request #4531
Opened 2023-06-16 23:44 UTC by just-a-node

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2023-06-17 07:31 UTC, rhlsthrm approved these changes

2023-06-17 07:33 UTC, carlomazzaferro approved these changes

2023-06-19 12:03 UTC, rhlsthrm requested changes

2023-06-23 06:35 UTC, just-a-node commented on ops/testnet/staging/core/main.tf
> +  max_capacity     = 300
It looks the same?

2023-06-23 06:37 UTC, just-a-node commented on ops/testnet/staging/core/main.tf
> +  max_capacity     = 300
It looks the same?

2023-06-23 13:48 UTC, rhlsthrm approved these changes

2023-06-23 13:48 UTC, merged