feat: add BTRST data
connext/monorepo pull request #4773
Opened 2023-08-03 09:50 UTC by multiart

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

[ChainData PR](https://github.com/connext/chaindata/pull/86)

2023-08-03 14:48 UTC, rhlsthrm approved these changes

2023-08-07 07:17 UTC, prathmeshkhandelwal1 commented
Verified. Lgtm. Minter role for connext contracts has also been granted. 
Thank @multiart , Approving this.

2023-08-07 07:17 UTC, prathmeshkhandelwal1 approved these changes

2023-08-18 09:04 UTC, prathmeshkhandelwal1 requested changes

2023-08-18 09:04 UTC, prathmeshkhandelwal1 commented on packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
> +      },
You need to add cap here as well.

Reference Link: https://github.com/connext/monorepo/blob/79dae16d9f88f19cfd8a06d3a567899fc920ed92/packages/deployments/contracts/src/cli/init/config/mainnet/production.ts#L24

2023-08-23 01:27 UTC, liu-zhipeng approved these changes

2023-08-29 08:42 UTC, prathmeshkhandelwal1 approved these changes

2023-08-29 08:44 UTC, prathmeshkhandelwal1 commented
@just-a-node , Can't merge as all commits are not signed.

2023-08-29 13:58 UTC, merged