Chore: add alcx to test net
connext/monorepo pull request #4833
Opened 2023-08-22 19:48 UTC by Hesnicewithit

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2023-08-25 10:12 UTC, prathmeshkhandelwal1 requested changes
https://goerli.etherscan.io/address/0x303241e2B3b4aeD0bb0F8623e7442368FED8Faf3

Can you verify this contract implementation as well, so that we can verify the token details.

2023-08-25 21:44 UTC, just-a-node approved these changes

2023-08-29 08:41 UTC, prathmeshkhandelwal1 approved these changes

2023-08-29 08:55 UTC, liu-zhipeng approved these changes

2023-08-29 09:02 UTC, prathmeshkhandelwal1 commented
@just-a-node , Not all commits are signed.

2023-08-29 10:47 UTC, merged