Radar token update
connext/monorepo pull request #4892
Opened 2023-09-14 08:17 UTC by Sonmezturk

I dont know what cap should be, can you help me about cap ? 

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2023-09-14 14:53 UTC, prathmeshkhandelwal1 requested changes

2023-09-14 14:53 UTC, prathmeshkhandelwal1 commented on packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
> +        address: "0x44709a920fCcF795fbC57BAA433cc3dd53C44DbE",
Hey, You have to add xERC20 address here for the whitelisting

2023-09-14 15:32 UTC, prathmeshkhandelwal1 requested changes

2023-09-14 15:32 UTC, prathmeshkhandelwal1 commented on packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
> +      name: "RADAR",
Name should be `xRADAR`

2023-10-13 07:34 UTC, prathmeshkhandelwal1 approved these changes

2023-10-13 08:23 UTC, sanchaymittal approved these changes

2023-10-18 10:00 UTC, sanchaymittal commented
Seeing ci/cd failing, @prathmeshkhandelwal1

2023-10-18 17:08 UTC, just-a-node approved these changes

2023-10-20 02:59 UTC, sanchaymittal approved these changes

2023-10-20 02:59 UTC, merged