Release packages for base goerli
connext/monorepo pull request #5363
Opened 2023-12-16 07:14 UTC by preethamr

## Description

Release packages for base goerli

## Type of change

- [ ] Docs change / dependency upgrade
- [x] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2023-12-16 10:31 UTC, liu-zhipeng submitted a review, later dismissed

2023-12-16 11:59 UTC, liu-zhipeng approved these changes

2023-12-16 17:53 UTC, LayneHaber requested changes
changeling

2024-03-18 22:25 UTC, preethamr commented
Closing this as not needed.

2024-03-18 22:25 UTC, closed without merging