feat: InrETH
connext/monorepo pull request #5707
Opened 2024-02-15 09:59 UTC by mellaught

## Description

Added **InrETH** and its representation on Goerli and Mumbai

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes

## Related pull request(s)

2024-02-16 11:09 UTC, prathmeshkhandelwal1 requested changes

2024-02-16 11:09 UTC, prathmeshkhandelwal1 commented on packages/deployments/contracts/src/cli/init/config/testnet/production.ts
> +        domain: "1735353714",
change this to pseudo domain. 
Example:
https://github.com/connext/monorepo/blob/dc6a1fd74bf5a1448bdb1cef9006348d60e47031/packages/deployments/contracts/src/cli/init/config/testnet/production.ts#L262

2024-02-16 11:09 UTC, prathmeshkhandelwal1 commented on packages/deployments/contracts/src/cli/init/config/testnet/production.ts
> +        address: "0x928c4b8E677E55C2829D0B4e3BdD3aC80226527D",
This should be `XERC20` address

2024-02-20 11:00 UTC, prathmeshkhandelwal1 approved these changes

2024-02-27 21:09 UTC, prathmeshkhandelwal1 approved these changes

2024-02-27 21:12 UTC, just-a-node approved these changes

2024-02-29 06:36 UTC, prathmeshkhandelwal1 approved these changes

2024-03-01 07:15 UTC, just-a-node approved these changes

2024-03-08 03:47 UTC, liu-zhipeng approved these changes

2024-03-08 05:18 UTC, merged