feat: add xPufETH in bridge config
connext/monorepo pull request #6334
Opened 2024-08-02 09:06 UTC by ksatyarth2

## Description
Add xPufETH for bridging config on Mainnet and BSC network

## Type of change

- [ ] Docs change / dependency upgrade
- [x] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2024-08-05 07:20 UTC, prathmeshkhandelwal1 requested changes

2024-08-05 07:20 UTC, prathmeshkhandelwal1 commented on packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
> +        domain: "6648936",
this should be pseudo domain

2024-08-05 07:20 UTC, prathmeshkhandelwal1 commented on packages/deployments/contracts/src/cli/init/config/mainnet/production.ts
> +        domain: "6648936",
`domain: "11111"`

2024-08-07 17:31 UTC, just-a-node commented
Added to whitelist branch.

2024-08-07 17:31 UTC, closed without merging