feat: rm dai, klp, kp3r, next, testvotes, usdc, usdt
connext/monorepo pull request #6362
Opened 2024-09-27 20:40 UTC by just-a-node

And xlayer from getSupportedd in sdkserver.

## Description

## Type of change

- [ ] Docs change / dependency upgrade
- [x] Configuration / tooling changes
- [ ] Refactoring
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

## Related Issue(s)

Fixes 

## Related pull request(s)

2024-09-27 20:45 UTC, preethamr submitted a review, later dismissed

2024-09-27 22:17 UTC, LayneHaber requested changes

2024-09-27 22:17 UTC, LayneHaber commented on ops/mainnet/prod/backend/config.tf
> +          "0x4200000000000000000000000000000000000006"
weth shouldn't be disabled?

2024-09-27 23:54 UTC, preethamr approved these changes

2024-09-28 22:19 UTC, LayneHaber approved these changes

2024-09-28 22:53 UTC, merged